name: Node.js CI

on:
  schedule:
    - cron: '37 19 * * *'
  workflow_dispatch:

jobs:
  update:

    runs-on: ubuntu-latest

    steps:
      - name: Install packages
        run: |
          sudo apt install npm
          npm install -g genpac

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3
        with:
          repository: leozhaozheng/genpacjs
          path: genpacjs

      - uses: actions/checkout@v3
        with:
          repository: gfwlist/gfwlist
          path: gfwlist

      - uses: leozhaozheng/git-config-user@master
        with:
          path: .

      - name: update
        run: |
          genpac --proxy "SOCKS5 ubuntu:1088; SOCKS ubuntu:1088; DIRECT;" -o gfwlist_ios.pac
          
          git add -f gfwlist_ios.pac
          git commit -m "[$(LANG=C date)] auto update" || exit 0
          
          [ -n "${{ secrets.READ_ONLY }}" ] && git show && exit 0
          
          git push origin dev
